### ISSUE TITLE
why can define that mu,omega = torch.unbind(self.parameterization(y).reshape(-1,self.num_eigenvalues,2),-1) ?

### ISSUE THREAD

**Issue by zc645080234** [mlpotter/DeepKoopmanLusch#4]
In this papar, I don't know where the mu and omega come, so in the codes,  do you have any basis for this?

**Comment by mlpotter** [comment]
In the paper, the way the matrix K is defined for the continuous spectrum (in equation 4) has mu and omega
![image](https://user-images.githubusercontent.com/35242331/219956714-aa664376-3d85-4896-ae35-a519112edf67.png)
https://www.nature.com/articles/s41467-018-07210-0

**Comment by zc645080234** [comment]
> In the paper, the way the matrix K is defined for the continuous spectrum (in equation 4) has mu and omega ![image](https://user-images.githubusercontent.com/35242331/219956714-aa664376-3d85-4896-ae35-a519112edf67.png) https://www.nature.com/articles/s41467-018-07210-0

Thank you for your answer. Recently I learn koopman, and try to reproduce the results of  deepkoopman. Your codes is very nice, which helps me a lot.
You mean that K is defined above( I already know the derivation of the definition )， and the neural network automatically fits the K matrix during the trainings.
